---
### https://github.com/ansible/ansible-examples/

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql-server
   - MySQL-python
   - libsemanage-python
  tags: [deployment, mysql]

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  tags: [deployment, mysql]

- name: Create Mysql configuration file
  template: src=my.cnf dest=/etc/
  notify: restart mysql
  tags: [deployment, mysql]

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
  tags: [deployment, mysql]
