---
- name: reload httpd
  service: name=httpd state=reloaded enabled=yes

- name: restart pacemaker
  service: name=pacemaker state=restarted enabled=yes

- name: restart corosync
  service: name=corosync state=restarted enabled=yes
