---
- hosts: proxy
  remote_user: vagrant
  sudo: yes
  gather_facts: no
  vars_files:
  	- vars/certs.yml
  	- vars/proxy.yml
  roles:
  	- nginx

- hosts: webservers
  remote_user: vagrant
  sudo: yes
  gather_facts: no
  vars_files:
    - vars/gluster.yml
  roles:
    - ha


