---
- hosts: proxy
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/certs.yml
    - vars/proxy.yml
  roles:
    - nginx

- hosts: web
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/gluster.yml
  roles:
    - glusterfs
    - httpd


