---
- hosts: all
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  roles:
    - base

- hosts: proxy
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/certs.yml
  roles:
    - nginx
    - clustering

- hosts: web
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/certs.yml
  roles:
    - glusterfs
    - httpd
    - clustering

- hosts: db
  remote_user: vagrant
  sudo: yes
  gather_facts: yes
  roles:
    - mysql
    - clustering

