---
- name: Mount GlusterFS volume
  mount: fstype=glusterfs
         name={{ gluster.mount_dir }}
         state=mounted
         src={{ groups['web'][0] }}:/{{ gluster.vol_name}}
         opts="defaults,_netdev"
  register: mount_result
  when: groups['gluster_slaves'] and "'remount' not in mount_result.stdout"
  tags: [deployment, glusterfs]

- name: Install httpd
  yum: name=httpd
       state=present
       update_cache=yes
  tags: [deployment, httpd]

- name: Make sure httpd is running but not on startup
  service: name=httpd
           state=started
           enabled=no
  tags: [deployment, httpd]

- name: Copy index html
  template: src=index.html
            dest=/var/www/html/
  tags: [configuration, httpd]

- name: Make sure log folder exists
  file: path={{ httpd.log_folder }}
        state=directory
        owner=apache
        group=apache
  tags: [configuration, httpd]

- name: Copy http config file
  template: src=httpd.conf
            dest=/etc/httpd/conf/
            owner=apache
            group=apache
  notify: reload httpd
  tags: [configuration, httpd]
