---
- name: Mount GlusterFS volume
  mount: fstype=glusterfs
         name={{ gluster_mount_dir }}
         state=mounted
         src={{ groups['web'][0] }}:/{{ gluster_vol_name}}
         opts="defaults,_netdev"
  register: mount_result
  when: groups['gluster_slaves'] and "'remount' not in mount_result.stdout"
  tags: deployment

- name: Install httpd
  yum: name=httpd
       state=present
       update_cache=yes
  tags: deployment

- name: Copy index html
  template: src=index.html
            dest={{ gluster_mount_dir }}
  tags: configuration

- name: Copy server-status virtualhost
  template: src=monitor.conf
            dest=/etc/httpd/conf.d/
  notify: reload httpd
  tags: configuration

