---
- name: Copy public key to hosts
  authorized_key: user={{ item }}
                  key="{{ cluster.ssh_pub_key }}"
  with_items:
    - vagrant
  tags: [cluster, deployment]

- name: Copy private key
  copy: content="{{ certs.cluster_rsa }}"
        dest=/home/{{ item }}/.ssh/cluster_rsa
        mode=0600
        owner={{ item }}
        group={{ item }}
  with_items:
    - vagrant
  tags: [cluster, deployment]

- name: Copy ssh config
  copy: src=config
        dest=/home/{{ item }}/.ssh/
        mode=0600
        owner={{ item }}
        group={{ item }}
  with_items:
    - vagrant
  tags: [cluster, deployment]

- name: Install base software
  yum: name={{ item }}
       state=present
       update_cache=yes
  with_items:
    - pacemaker
    - corosync
    - cman
  tags: [cluster, deployment]

- name: Make sure corosync is off
  service: name=corosync
           state=stopped
           enabled=no
  tags: [cluster, deployment]

- name: Set no quorum to the clusters
  lineinfile: backup=yes
              dest=/etc/sysconfig/cman
              state=present
              line="CMAN_QUORUM_TIMEOUT=0"
  tags: [cluster, deployment]

- name: Copy corosync configuration
  template: src=corosync.conf
            dest=/etc/corosync/
  tags: [cluster, configuration]

- name: Cluster config
  template: src=cluster.conf
            dest=/etc/cluster/
  tags: [cluster, configuration]

- name: Start cluster on first node
  service: name=pacemaker state=started enabled=yes
  run_once: true
  register: cluster_status
  tags: [cluster, configuration]

- name: Start cluster on slaves if master is up
  service: name=pacemaker state=started enabled=yes
  when: ansible_hostname in groups['gluster_slaves'] and "cluster_status.rc == 0"
  tags: [cluster, configuration]

- name: Copy server-status virtualhost
  template: src=monitor.conf
            dest=/etc/httpd/conf.d/
  notify: reload httpd
  tags: [cluster, configuration]


