---
## Before attempting to create FS you must create a partition table on the new disk.
## You can use fdisk, cfisk, sfdisk..
- name: Create ext4 filesystem
  filesystem: fstype=ext4
              dev=/dev/sdb1
              opts="-cc"
              force=yes
  tags: filesystem

- name: Mount filesystem
  mount: name=/srv/sdb1
         src=/dev/sdb1
         fstype=ext4
         state=mounted
         opts="defaults"
  tags: filesystem

- name: Ensure brick directory exists
  file: path={{ item }}
        state=directory
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"
  tags: filesystem

- name: Copy gluster gluster repo
  copy: src=gluster.repo
        dest=/etc/yum.repos.d/
  tags: [deployment, gluterfs]

- name: Install GlusterFS
  yum: name={{ item }}
       state=present
       update_cache=yes
  with_items:
    - glusterfs
    - glusterfs-server
    - glusterfs-fuse
  notify: start gluster
  tags: [deployment, glusterfs]

- name: Check if Gluster volumes already exist
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info
  tags: glusterfs

- name: Connect peers
  command: gluster peer probe {{ item }}
  #when: "'Volume Name: {{ gluster_vol_name }}' not in gluster_volume_info.stdout"
  register: gluster_probe_result
  changed_when: "'already in peer list' not in gluster_probe_result.stdout"
  with_items:
    - "{{ hostvars[groups['web'][1]]['ansible_eth1']['ipv4']['address'] }}"
    - "{{ hostvars[groups['web'][2]]['ansible_eth1']['ipv4']['address'] }}"
    - "{{ hostvars[groups['web'][3]]['ansible_eth1']['ipv4']['address'] }}"
  run_once: true
  tags: glusterfs

- name: Create and start gluster volume
  gluster_volume: state=started
                  name="{{ gluster_vol_name }}"
                  replicas=2
                  brick="{{gluster_brick_dir }}"
                  rebalance=yes
                  cluster="{{ gluster_cluster }}"
                  force=true

  #when: "'Volume Name: {{ gluster_vol_name }}' not in gluster_volume_info.stdout"
  run_once: true
  ignore_errors: yes
  tags: glusterfs



