---
- name: Install Apache
  yum: name=httpd
        state=present
        disablerepo=*
        enablerepo=base
  tags: deployment

- name: Upgrade git to latest version
  yum: name=git
        state=latest
  tags: deployment

- name: Clone wikimedia
  git: repo=https://gerrit.wikimedia.org/r/p/mediawiki/core.git
       dest=/var/www/html/
       ssh_opts="-o StrictHostKeyChecking=no"
       version=1.9.6
  tags: deployment

